version: '3.8'

services:
  frontend:
    build: 
      context: ./WebApp/React
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./WebApp/React:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  backend:
    build: 
      context: ./WebApp/FastAPI
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./WebApp/FastAPI:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  tensorflow:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8989:8989"
    volumes:
      - .:/tf/workdir
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  node_modules: